server:
  servlet:
    context-path: /api
spring:
  application:
    name: sos-api
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
      org:
        hibernate:
          envers:
            store_data_at_delete: true
            audit_table_suffix: _history
    open-in-view: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}:%line - %msg%n"
  level:
    root: INFO
    org:
      springframework:
        web: debug
      hibernate: error

# SOS DataSource
sos:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@//oracle-homepage-20230303.ciju3jwynmki.ap-northeast-2.rds.amazonaws.com:1521/ORCL
    username: siteadmin
    password: site2009
    hikari:
      maximum-pool-size: 10

# SIS DataSource
sis:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@//oracle-homepage-20230303.ciju3jwynmki.ap-northeast-2.rds.amazonaws.com:1521/ORCL
    username: siseer
    password: siseer
    hikari:
      maximum-pool-size: 10